# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e27e26e38389ffa5ca6afdfc507ab09953ad7a7200044cfdbf8bdfe216b6e488c99eaa5438579b99a4c6f566853c9a831eee0418f478a287b3a6e0f00f19ecf

test:
  secret_key_base: 169b810e03b56bc02f24ea79e6e2423aaf78704b892fe001af31d457f1d34d3931d51681c29d323fb9dde97df7194510a2df6841df313bad11b5a27463c0bb68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
